---
language: python
python: 2.7
services: docker

env:
  matrix:
    - MOLECULE_DISTRO: centos7
    # - MOLECULE_DISTRO: ubuntu1804
    # - MOLECULE_DISTRO: debian9

install:
  # Install test dependencies.
  - pip install testinfra molecule docker netaddr

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
